server:
  port: 9001
  servlet:
    context-path: /services
security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user
#      user-info-uri: http://localhost:9000/services/user